// WVSU Space — `lib/firebase_options.dart`
// Platform-specific Firebase configuration used at app startup.
// Note: this file holds Firebase config values for each platform.
// ignore_for_file: type=lint
/* Purpose: Provide Firebase configuration for each platform so the app can start and use Firebase services. These values were generated by the FlutterFire CLI. Keep platform config private in production. */
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Purpose: Platform-specific Firebase settings the app uses at startup. This example right here below is already here when the app initializes, the project I mean sorry.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          // Simple: we haven't set config for Linux here since this is not for linux hehe.
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkulfMCmBIbxtjWsX44V5Hj2qaraOVUgk',
    appId: '1:1045242125451:web:ab49e9c5a6b0a0d6ec088e',
    messagingSenderId: '1045242125451',
    projectId: 'wvsu-space',
    authDomain: 'wvsu-space.firebaseapp.com',
    storageBucket: 'wvsu-space.firebasestorage.app',
    measurementId: 'G-WDE5DY38MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd11L7o5vhkoUnhLwdy69ehVnyZZk6gx4',
    appId: '1:1045242125451:android:caf5a6d0d1036743ec088e',
    messagingSenderId: '1045242125451',
    projectId: 'wvsu-space',
    storageBucket: 'wvsu-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIdCA6TZWVXGRVKfkrGpiNjD33QDohHdg',
    appId: '1:1045242125451:ios:5678be0a045e7456ec088e',
    messagingSenderId: '1045242125451',
    projectId: 'wvsu-space',
    storageBucket: 'wvsu-space.firebasestorage.app',
    iosBundleId: 'com.example.wvsuSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIdCA6TZWVXGRVKfkrGpiNjD33QDohHdg',
    appId: '1:1045242125451:ios:5678be0a045e7456ec088e',
    messagingSenderId: '1045242125451',
    projectId: 'wvsu-space',
    storageBucket: 'wvsu-space.firebasestorage.app',
    iosBundleId: 'com.example.wvsuSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkulfMCmBIbxtjWsX44V5Hj2qaraOVUgk',
    appId: '1:1045242125451:web:65ba2127b24d3977ec088e',
    messagingSenderId: '1045242125451',
    projectId: 'wvsu-space',
    authDomain: 'wvsu-space.firebaseapp.com',
    storageBucket: 'wvsu-space.firebasestorage.app',
    measurementId: 'G-28EYFVGBFM',
  );
}
